# Generated by Django 4.2.23 on 2025-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsHistory',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_params', models.JSONField()),
                ('last_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
