# Generated by Django 4.2.23 on 2025-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=200)),
                ('sub_section', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
