# Generated by Django 4.2.23 on 2026-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_apiparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
    ]
